spring:
  application:
    name: noriter-api
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring.modulith:
  events:
    jdbc:
      schema-initialization:
        enabled: true
    republish-outstanding-events-on-restart: true
