CREATE TABLE wall_post (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT,
    guest_token     VARCHAR(64),
    guest_name      VARCHAR(12),
    guest_character VARCHAR(16),
    visitor_hash    VARCHAR(64)  NOT NULL,
    post_day        DATE         NOT NULL,
    content         VARCHAR(200) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_wall_post PRIMARY KEY (id),
    CONSTRAINT fk_wall_post_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT uk_wall_post_user_day UNIQUE (user_id, post_day),
    CONSTRAINT uk_wall_post_guest_day UNIQUE (guest_token, post_day)
);

CREATE INDEX ix_wall_post_day ON wall_post (post_day);
