-- 초기 스키마. 로그인 유저와 게임 점수만 둔다. 댓글은 다음 마이그레이션에서.
CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(32)  NOT NULL,          -- google, apple ...
    provider_id VARCHAR(255) NOT NULL,
    nickname    VARCHAR(40)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_app_user_provider UNIQUE (provider, provider_id)
);

CREATE TABLE game_score (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    VARCHAR(32) NOT NULL,            -- 프론트 registry 의 game id ("2048")
    user_id    BIGINT      NOT NULL REFERENCES app_user (id),
    score      BIGINT      NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_game_score_leaderboard ON game_score (game_id, score DESC, created_at);
CREATE INDEX ix_game_score_user ON game_score (user_id, game_id);
