CREATE TABLE appUser (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider   VARCHAR(32)  NOT NULL,
    providerId VARCHAR(255) NOT NULL,
    nickname   VARCHAR(40)  NOT NULL,
    createdAt  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uqAppUserProvider UNIQUE (provider, providerId)
);

CREATE TABLE gameScore (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gameId    VARCHAR(32) NOT NULL,
    userId    BIGINT      NOT NULL REFERENCES appUser (id),
    score     BIGINT      NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ixGameScoreLeaderboard ON gameScore (gameId, score DESC, createdAt);
CREATE INDEX ixGameScoreUser ON gameScore (userId, gameId);
