CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider    VARCHAR(32)  NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    nickname    VARCHAR(40)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_provider UNIQUE (provider, provider_id)
);

CREATE TABLE game_score (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    game_id    VARCHAR(32) NOT NULL,
    user_id    BIGINT      NOT NULL,
    score      BIGINT      NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_game_score PRIMARY KEY (id),
    CONSTRAINT fk_game_score_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_game_score_leaderboard ON game_score (game_id, score DESC, created_at);
CREATE INDEX ix_game_score_user ON game_score (user_id, game_id);

CREATE TABLE site_visit (
    visit_day   DATE   NOT NULL,
    visit_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_site_visit PRIMARY KEY (visit_day)
);

INSERT INTO app_user (id, provider, provider_id, nickname, created_at)
SELECT id, provider, providerId, nickname, createdAt FROM appUser;

INSERT INTO game_score (id, game_id, user_id, score, created_at)
SELECT id, gameId, userId, score, createdAt FROM gameScore;

INSERT INTO site_visit (visit_day, visit_count)
SELECT visitDay, count FROM siteVisit;

DROP TABLE gameScore;
DROP TABLE appUser;
DROP TABLE siteVisit;
