ALTER TABLE app_user ADD COLUMN password_hash VARCHAR(100);
ALTER TABLE app_user ADD COLUMN email VARCHAR(255);
ALTER TABLE app_user ADD COLUMN character_id VARCHAR(32);
ALTER TABLE app_user ADD COLUMN presence VARCHAR(16) NOT NULL DEFAULT 'ONLINE';

CREATE TABLE friend (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT NOT NULL,
    friend_id  BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_friend PRIMARY KEY (id),
    CONSTRAINT fk_friend_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id) REFERENCES app_user (id)
);

CREATE INDEX ix_friend_user ON friend (user_id);

CREATE TABLE notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    kind       VARCHAR(32)  NOT NULL,
    title      VARCHAR(120) NOT NULL,
    body       VARCHAR(400),
    link       VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at    TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_notification_user ON notification (user_id, created_at DESC);
