ALTER TABLE app_user ADD COLUMN role VARCHAR(16) NOT NULL DEFAULT 'USER';

CREATE TABLE game_play (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    game_id      VARCHAR(32) NOT NULL,
    play_mode    VARCHAR(8)  NOT NULL,
    room_id      VARCHAR(8),
    user_id      BIGINT,
    player_count INT         NOT NULL,
    score        BIGINT,
    finish_rank  INT,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_game_play PRIMARY KEY (id),
    CONSTRAINT fk_game_play_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_game_play_game_time ON game_play (game_id, created_at);
CREATE INDEX ix_game_play_time ON game_play (created_at);
