CREATE TABLE conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kind            VARCHAR(8)  NOT NULL,
    dm_key          VARCHAR(64),
    last_message_at TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_conversation PRIMARY KEY (id),
    CONSTRAINT uk_conversation_dm_key UNIQUE (dm_key)
);

CREATE TABLE conversation_member (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id      BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    last_read_message_id BIGINT NOT NULL DEFAULT 0,
    joined_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_conversation_member PRIMARY KEY (id),
    CONSTRAINT uk_conversation_member UNIQUE (conversation_id, user_id),
    CONSTRAINT fk_conversation_member_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT fk_conversation_member_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_conversation_member_user ON conversation_member (user_id);

CREATE TABLE message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT       NOT NULL,
    sender_id       BIGINT       NOT NULL,
    body            VARCHAR(500) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_message PRIMARY KEY (id),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES app_user (id)
);

CREATE INDEX ix_message_conversation ON message (conversation_id, id);
