CREATE TABLE word_dictionary (
    jamo    VARCHAR(6) NOT NULL,
    word    VARCHAR(8) NOT NULL,
    meaning TEXT,
    CONSTRAINT pk_word_dictionary PRIMARY KEY (jamo)
);

CREATE TABLE word_puzzle (
    number  INT        NOT NULL,
    jamo    VARCHAR(6) NOT NULL,
    word    VARCHAR(8) NOT NULL,
    meaning TEXT,
    CONSTRAINT pk_word_puzzle PRIMARY KEY (number)
);

CREATE TABLE word_result (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT   NOT NULL,
    number     INT      NOT NULL,
    attempts   SMALLINT,
    hard       BOOLEAN  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_word_result PRIMARY KEY (id),
    CONSTRAINT uk_word_result_user_number UNIQUE (user_id, number),
    CONSTRAINT fk_word_result_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
