CREATE TABLE word_guess (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT     NOT NULL,
    number     INT        NOT NULL,
    seq        SMALLINT   NOT NULL,
    jamo       VARCHAR(6) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_word_guess PRIMARY KEY (id),
    CONSTRAINT uk_word_guess_user_number_seq UNIQUE (user_id, number, seq),
    CONSTRAINT fk_word_guess_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
